#!/usr/bin/env node
/**
 * Production safe-test guards + a real bcrypt round-trip through the classifier.
 *
 * Two halves:
 *
 *   1. Guard policy (offline). The rules that stop an Admin operation touching a
 *      real customer in `mydesckpro`, and that refuse a revoked credential.
 *      These must be correct BEFORE a working credential exists.
 *
 *   2. Real bcrypt (needs PGURL). Hashes are generated by pgcrypto's
 *      crypt()/gen_salt('bf') — actual bcrypt, not a fixture string — then run
 *      through parseBcrypt, classifyAccount and buildImportRecord.
 *
 * SCOPE LIMIT, stated plainly: pgcrypto bcrypt is the same algorithm and the
 * same modular-crypt format GoTrue emits, but it is NOT the same producer.
 * This proves the classifier handles real bcrypt correctly. It does NOT prove
 * that a hash written by Supabase GoTrue is accepted by Firebase Auth. That
 * remains blocked on a safe Admin credential and a non-production GoTrue.
 *
 *   node migration/tests/firebase-safety.test.mjs           # guards only
 *   PGURL=postgres://... node migration/tests/firebase-safety.test.mjs
 */

import assert from 'node:assert/strict';
import { writeFileSync, rmSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  inspectCredential, assertCredentialUsable, REVOKED_KEY_IDS,
  isTestEmail, makeTestEmail, assertTestIdentity, assertSafeToCreate,
  buildCleanupManifest, TEST_EMAIL_PREFIX,
} from '../tools/lib/firebase-safety.mjs';
import { parseBcrypt, classifyAccount, buildImportRecord } from '../tools/lib/auth-classify.mjs';

let pass = 0;
const failures = [];
async function test(name, fn) {
  try { await fn(); pass++; console.log(`  ok    ${name}`); }
  catch (e) { failures.push({ name, message: e.message }); console.log(`  FAIL  ${name}\n        ${e.message}`); }
}

const REVOKED_ID = 'b1ceff39a8d768ffe9d5d98fe459fbdd2dcc6ca8';
const tmp = mkdtempSync(join(tmpdir(), 'fbsafety-'));

// ================================================================ credentials

console.log('[credentials] revoked-key refusal\n');

function credFile(name, obj) {
  const p = join(tmp, name);
  writeFileSync(p, JSON.stringify(obj), 'utf8');
  return p;
}

const FAKE_KEY = '-----BEGIN PRIVATE KEY-----\nnot-a-real-key\n-----END PRIVATE KEY-----\n';

await test('inspectCredential never returns private key material', async () => {
  const p = credFile('ok.json', {
    type: 'service_account', project_id: 'mydesckpro',
    private_key_id: 'aaaa1111bbbb2222cccc3333dddd4444eeee5555',
    private_key: FAKE_KEY, client_email: 'x@y.iam.gserviceaccount.com',
  });
  const info = inspectCredential(p);
  const serialised = JSON.stringify(info);
  assert.ok(!serialised.includes('PRIVATE KEY'), 'key material leaked into the inspection result');
  assert.ok(!('private_key' in info), 'private_key present on the returned object');
  assert.equal(info.projectId, 'mydesckpro');
});

await test('the exposed key id is on the revoked list', async () => {
  assert.ok(REVOKED_KEY_IDS.has(REVOKED_ID));
});

await test('a revoked credential is REFUSED with a machine-readable code', async () => {
  const p = credFile('revoked.json', {
    type: 'service_account', project_id: 'mydesckpro',
    private_key_id: REVOKED_ID, private_key: FAKE_KEY,
    client_email: 'firebase-adminsdk-fbsvc@mydesckpro.iam.gserviceaccount.com',
  });
  const info = inspectCredential(p);
  assert.equal(info.isRevoked, true);
  assert.equal(info.isProductionProject, true);
  assert.throws(() => assertCredentialUsable(info), (e) => e.code === 'CREDENTIAL_REVOKED');
});

await test('a non-revoked service account passes the gate', async () => {
  const info = inspectCredential(join(tmp, 'ok.json'));
  assert.equal(info.isRevoked, false);
  assert.equal(assertCredentialUsable(info), true);
});

await test('a non-service-account credential is refused', async () => {
  const p = credFile('user.json', { type: 'authorized_user', project_id: 'mydesckpro' });
  assert.throws(() => assertCredentialUsable(inspectCredential(p)),
    (e) => e.code === 'CREDENTIAL_WRONG_TYPE');
});

await test('unparseable credential is refused, not ignored', async () => {
  const p = join(tmp, 'broken.json');
  writeFileSync(p, '{not json', 'utf8');
  assert.throws(() => assertCredentialUsable(inspectCredential(p)),
    (e) => e.code === 'CREDENTIAL_UNREADABLE');
});

// ================================================================ namespace

console.log('\n[namespace] production identity boundary\n');

await test('generated test emails are inside the namespace', async () => {
  const a = makeTestEmail('a');
  assert.ok(a.startsWith(TEST_EMAIL_PREFIX), a);
  assert.ok(isTestEmail(a));
  assert.equal(makeTestEmail('A  B!'), `${TEST_EMAIL_PREFIX}a--b@mydesck-migration.invalid`);
});

await test('real-looking customer emails are rejected', async () => {
  for (const e of [
    'owner@agency.com', 'aseelshaheen621@gmail.com', 'kitchen@BurgerKing_a1b2.com',
    'migration-test@x.com',            // missing the double dash
    'x-migration-test--a@x.com',       // prefix not at the start
    'MIGRATION-TEST--a@x.com'.replace('MIGRATION-TEST--', 'migrationtest--'),
  ]) {
    assert.equal(isTestEmail(e), false, `should be rejected: ${e}`);
  }
});

await test('assertTestIdentity throws on a production email', async () => {
  assert.throws(
    () => assertTestIdentity({ email: 'owner@agency.com', uid: 'x' }, 'create'),
    (e) => e.code === 'OUTSIDE_TEST_NAMESPACE');
});

await test('assertTestIdentity rejects an oversized uid', async () => {
  assert.throws(
    () => assertTestIdentity({ email: makeTestEmail('a'), uid: 'x'.repeat(129) }),
    (e) => e.code === 'INVALID_UID');
});

await test('creating over an existing email is refused, never adopted', async () => {
  assert.throws(
    () => assertSafeToCreate(
      { email: makeTestEmail('a'), uid: 'u1' },
      { byEmail: { uid: 'someone-elses-uid' } }),
    (e) => e.code === 'EMAIL_ALREADY_EXISTS');
});

await test('creating over an existing uid is refused, never overwritten', async () => {
  assert.throws(
    () => assertSafeToCreate({ email: makeTestEmail('b'), uid: 'u1' }, { byUid: { email: 'x' } }),
    (e) => e.code === 'UID_ALREADY_EXISTS');
});

await test('a clean create is allowed', async () => {
  assert.equal(assertSafeToCreate({ email: makeTestEmail('c'), uid: 'u2' }, {}), true);
});

// ================================================================ manifest

console.log('\n[manifest] cleanup accounting\n');

await test('manifest records every identity and never self-approves deletion', async () => {
  const created = ['a', 'b', 'c'].map((l, i) => ({
    uid: `uid-${i}`, email: makeTestEmail(l), createdAt: '2026-09-09T00:00:00Z',
  }));
  const m = buildCleanupManifest(created, { projectId: 'mydesckpro' });
  assert.equal(m.count, 3);
  assert.equal(m.identities.length, 3);
  assert.equal(m.isProductionProject, true);
  assert.equal(m.deletionApproved, false, 'tooling must never pre-approve deletion');
});

await test('manifest refuses an identity outside the namespace', async () => {
  assert.throws(
    () => buildCleanupManifest([{ uid: 'u', email: 'real@customer.com' }], { projectId: 'mydesckpro' }),
    (e) => e.code === 'OUTSIDE_TEST_NAMESPACE');
});

// ================================================================ real bcrypt

const PGURL = process.env.PGURL || process.env.DATABASE_URL;

if (!PGURL) {
  console.log('\n[bcrypt] NOT RUN — no PGURL. Real-bcrypt classifier proof did not execute.');
} else {
  console.log('\n[bcrypt] real hashes from pgcrypto (not fixtures)\n');
  const { default: pg } = await import('pg');
  const c = new pg.Client({ connectionString: PGURL });
  await c.connect();
  await c.query("SET client_encoding TO 'UTF8'");
  await c.query('CREATE EXTENSION IF NOT EXISTS pgcrypto');

  const PASSWORD = 'Correct-Horse-Battery-Staple-2026';
  const WRONG = 'Correct-Horse-Battery-Staple-2027';
  const UID = '3f2504e0-4f89-11d3-9a0c-0305e82c3301';

  // Real bcrypt, generated server-side. The value never leaves this process.
  const { rows: [{ h }] } = await c.query(
    `SELECT crypt($1, gen_salt('bf', 10)) AS h`, [PASSWORD]);

  await test('pgcrypto produces a hash the classifier recognises as bcrypt', async () => {
    const r = parseBcrypt(h);
    assert.equal(r.ok, true, `parseBcrypt rejected a real bcrypt hash: ${String(h).slice(0, 4)}…`);
    assert.equal(r.cost, 10);
    assert.equal(r.unusualCost, false);
  });

  await test('the hash verifies against the right password and not the wrong one', async () => {
    const { rows: [ok] } = await c.query(`SELECT crypt($1, $2) = $2 AS v`, [PASSWORD, h]);
    const { rows: [bad] } = await c.query(`SELECT crypt($1, $2) = $2 AS v`, [WRONG, h]);
    assert.equal(ok.v, true, 'correct password did not verify');
    assert.equal(bad.v, false, 'wrong password verified — catastrophic');
  });

  await test('an account carrying a real hash classifies as transparent', async () => {
    const cl = classifyAccount({
      id: UID, email: 'owner@agency.example', encrypted_password: h,
      email_confirmed_at: '2026-01-01T00:00:00Z',
      has_business_profile: true, has_user_profile: true, has_oauth_identity: false,
    });
    assert.equal(cl.authClass, 'transparent');
    assert.equal(cl.blocking, false);
  });

  await test('the import record carries the real hash byte-identically', async () => {
    const rec = buildImportRecord({
      id: UID, email: 'owner@agency.example', encrypted_password: h,
      email_confirmed_at: '2026-01-01T00:00:00Z',
    });
    assert.equal(rec.uid, UID, 'uid must be preserved verbatim');
    assert.equal(rec.passwordHash.toString('utf8'), h, 'hash altered in transit');
    assert.deepEqual(rec.customClaims, { role: 'authenticated' });
  });

  await test('all bcrypt cost factors 4..14 round-trip through the classifier', async () => {
    for (const cost of [4, 8, 10, 12, 14]) {
      const { rows: [{ hh }] } = await c.query(
        `SELECT crypt($1, gen_salt('bf', $2)) AS hh`, [PASSWORD, cost]);
      const r = parseBcrypt(hh);
      assert.equal(r.ok, true, `cost ${cost} rejected`);
      assert.equal(r.cost, cost);
      assert.equal(r.unusualCost, cost < 10 || cost > 14, `cost ${cost} flagged wrongly`);
      const { rows: [v] } = await c.query(`SELECT crypt($1, $2) = $2 AS v`, [PASSWORD, hh]);
      assert.equal(v.v, true, `cost ${cost} did not verify`);
    }
  });

  await test('a corrupted real hash is rejected, not silently accepted', async () => {
    assert.equal(parseBcrypt(h.slice(0, -1)).ok, false, 'truncated hash accepted');
    assert.equal(parseBcrypt(h.replace('$2a$', '$2c$')).ok, false, 'unknown variant accepted');
  });

  await test('no hash reaches any string this tooling would emit', async () => {
    const cl = classifyAccount({
      id: UID, email: 'owner@agency.example', encrypted_password: h,
      has_business_profile: true, has_user_profile: true,
    });
    const { redact, toLedgerRows } = await import('../tools/lib/auth-classify.mjs');
    const emitted = JSON.stringify({
      ledger: toLedgerRows([{ id: UID, email: 'o@a.example', encrypted_password: h }], [cl]),
      redacted: redact({ passwordHash: h, encrypted_password: h }),
    });
    assert.ok(!emitted.includes(h), 'a real hash leaked into emitted output');
  });

  await c.end();
}

rmSync(tmp, { recursive: true, force: true });

console.log(`\n[firebase-safety] ${pass} passed, ${failures.length} failed`);
for (const f of failures) console.error(`  FAIL  ${f.name}\n        ${f.message}`);
process.exit(failures.length ? 1 : 0);
