import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bell, CheckCheck, Clock3, MessageCircle, Settings2, Trash2, X } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../../contexts/AuthContext';
import { useLanguage } from '../../contexts/LanguageContext';
import { clearCompletedTripNotifications, dismissTripNotification, fetchTripNotifications, getTripNotificationSettings, markAllTripNotificationsRead, markTripNotificationRead, saveTripNotificationSettings, snoozeTripNotification, type TripNotificationSettings } from '../../lib/tripNotifications';
import { Button } from '../travel-ui/Button';

interface Props { onClose: () => void; onOpenTrip: (id: string) => void; onOpenWhatsapp: (id: string, type: 'upcoming_trip' | 'cash_balance' | 'missing_information') => void }

export function TripNotificationCenter({ onClose, onOpenTrip, onOpenWhatsapp }: Props) {
  const { user } = useAuth();
  const { t, direction, language } = useLanguage();
  const client = useQueryClient();
  const [showSettings, setShowSettings] = useState(false);
  const [typeFilter, setTypeFilter] = useState('all');
  const notifications = useQuery({ queryKey: ['trip-notifications'], queryFn: fetchTripNotifications });
  const settingsQuery = useQuery({ queryKey: ['trip-notification-settings', user?.id], queryFn: () => getTripNotificationSettings(user!.id), enabled: Boolean(user?.id) });
  const [settings, setSettings] = useState<TripNotificationSettings | null>(null);
  useEffect(() => { if (settingsQuery.data) setSettings(settingsQuery.data); }, [settingsQuery.data]);
  const readMutation = useMutation({ mutationFn: markTripNotificationRead, onSuccess: () => client.invalidateQueries({ queryKey: ['trip-notifications'] }) });
  const actionMutation = useMutation({ mutationFn: async ({ action, id }: { action: 'all' | 'dismiss' | 'snooze' | 'clear'; id?: string }) => { if (action === 'all') return markAllTripNotificationsRead(); if (action === 'dismiss') return dismissTripNotification(id!); if (action === 'snooze') return snoozeTripNotification(id!, new Date(Date.now() + 86_400_000).toISOString()); return clearCompletedTripNotifications(); }, onSuccess: () => client.invalidateQueries({ queryKey: ['trip-notifications'] }) });
  const saveMutation = useMutation({ mutationFn: () => saveTripNotificationSettings(user!.id, settings!), onSuccess: () => { toast.success(t('trips.notifications.saved')); setShowSettings(false); client.invalidateQueries({ queryKey: ['trip-notification-settings'] }); } });
  const params = (value: unknown): Record<string, unknown> => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};
  const locale = language === 'he' ? 'he-IL' : language === 'ar' ? 'ar-EG' : 'en-US';
  const visible = (notifications.data || []).filter((item) => (!item.snoozed_until || item.snoozed_until <= new Date().toISOString()) && (typeFilter === 'all' || item.notification_type === typeFilter));
  const unread = (notifications.data || []).filter((item) => !item.read_at).length;
  const types = Array.from(new Set((notifications.data || []).map((item) => item.notification_type)));
  return <div className="fixed inset-0 z-[100] flex justify-end bg-slate-950/60" dir={direction} role="dialog" aria-modal="true" aria-labelledby="notification-title">
    <aside className="h-full w-full max-w-md overflow-y-auto bg-white shadow-2xl dark:bg-slate-950">
      <header className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-950"><h2 id="notification-title" className="flex items-center gap-2 text-lg font-bold"><Bell className="h-5 w-5"/>{t('trips.notifications.title')}<span className="rounded-full bg-sky-600 px-2 py-0.5 text-xs text-white">{unread}</span></h2><div className="flex"><Button size="icon" variant="ghost" onClick={() => actionMutation.mutate({ action: 'all' })} aria-label={t('trips.notifications.markAllRead')}><CheckCheck/></Button><Button size="icon" variant="ghost" onClick={() => actionMutation.mutate({ action: 'clear' })} aria-label={t('trips.notifications.clearCompleted')}><Trash2/></Button><Button size="icon" variant="ghost" onClick={() => setShowSettings((value) => !value)} aria-label={t('trips.notifications.settings')}><Settings2/></Button><Button size="icon" variant="ghost" onClick={onClose} aria-label={t('trips.close')}><X/></Button></div></header>
      {showSettings && settings && <section className="space-y-3 border-b border-slate-200 p-4 dark:border-slate-800"><h3 className="font-semibold">{t('trips.notifications.settings')}</h3>{(['upcoming_enabled', 'payment_enabled', 'cleanup_enabled', 'retention_enabled'] as const).map((key) => <label key={key} className="flex items-center justify-between gap-3 text-sm"><span>{t(`trips.notifications.${key}`)}</span><input type="checkbox" checked={settings[key]} onChange={(event) => setSettings({ ...settings, [key]: event.target.checked })}/></label>)}<label className="block text-sm">{t('trips.notifications.tripIntervals')}<input value={settings.trip_reminder_days.join(', ')} onChange={(event) => setSettings({ ...settings, trip_reminder_days: event.target.value.split(',').map(Number).filter((value) => Number.isInteger(value) && value >= 0 && value <= 365) })} className="mt-1 h-10 w-full rounded-lg border border-slate-300 bg-transparent px-3"/></label><label className="block text-sm">{t('trips.notifications.paymentIntervals')}<input value={settings.payment_reminder_days.join(', ')} onChange={(event) => setSettings({ ...settings, payment_reminder_days: event.target.value.split(',').map(Number).filter((value) => Number.isInteger(value) && value >= 0 && value <= 365) })} className="mt-1 h-10 w-full rounded-lg border border-slate-300 bg-transparent px-3"/></label><Button variant="primary" disabled={saveMutation.isPending || settings.trip_reminder_days.length === 0 || settings.payment_reminder_days.length === 0} onClick={() => saveMutation.mutate()}>{t('trips.save')}</Button></section>}
      <div className="border-b border-slate-200 p-3 dark:border-slate-800"><select value={typeFilter} onChange={(e) => setTypeFilter(e.target.value)} className="h-9 w-full rounded-lg border bg-transparent px-3"><option value="all">{t('trips.notifications.allTypes')}</option>{types.map((type) => <option key={type} value={type}>{t(`trips.notifications.types.${type}`)}</option>)}</select></div>
      <div>{notifications.isLoading ? <p className="p-5 text-slate-500">{t('auth.loading')}</p> : !visible.length ? <p className="p-8 text-center text-slate-500">{t('trips.notifications.empty')}</p> : visible.map((item) => <article key={item.id} className={`border-b border-slate-200 p-4 dark:border-slate-800 ${item.read_at ? 'opacity-65' : 'bg-sky-50/70 dark:bg-sky-950/20'}`}><button className="block w-full text-start" onClick={() => { if (!item.read_at) readMutation.mutate(item.id); if (item.trip_id) onOpenTrip(item.trip_id); }}><p className="font-semibold">{t(item.title_key, params(item.params))}</p><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{t(item.body_key, params(item.params))}</p><time className="mt-2 block text-xs text-slate-500">{new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(item.created_at))}</time></button><div className="mt-2 flex flex-wrap gap-2">{item.trip_id && <Button size="sm" variant="ghost" onClick={() => onOpenWhatsapp(item.trip_id!, item.notification_type === 'upcoming_trip' ? 'upcoming_trip' : item.notification_type === 'missing_critical_data' ? 'missing_information' : 'cash_balance')}><MessageCircle className="h-4 w-4"/>{t('trips.card.prepareWhatsapp')}</Button>}<Button size="sm" variant="ghost" onClick={() => actionMutation.mutate({ action: 'snooze', id: item.id })}><Clock3 className="h-4 w-4"/>{t('trips.notifications.snooze')}</Button><Button size="sm" variant="ghost" onClick={() => actionMutation.mutate({ action: 'dismiss', id: item.id })}><X className="h-4 w-4"/>{t('trips.notifications.dismiss')}</Button></div></article>)}</div>
    </aside>
  </div>;
}
