import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Archive, Copy, FilePlus2, Pencil, Search, Star, Trash2, X } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../../contexts/AuthContext';
import { useLanguage } from '../../contexts/LanguageContext';
import { createTemplateDataFromTrip, fetchTripTemplate, fetchTripTemplates, recordTripTemplateUse, saveTripTemplate, softDeleteTripTemplate, templateToTripDraft, toggleTripTemplateFavorite, updateTripTemplateStatus, type TripTemplate, type TripTemplateData, type TripTemplateType } from '../../lib/tripTemplates';
import type { Trip } from '../../types/trip';
import { Button } from '../travel-ui/Button';

interface Props { onClose: () => void; sourceTrip?: Trip; initialTemplateId?: string; onUse?: (draft: Trip) => void }

export function TripTemplatesPanel({ onClose, sourceTrip, initialTemplateId, onUse }: Props) {
  const { user } = useAuth(); const { t, direction } = useLanguage(); const client = useQueryClient();
  const [search, setSearch] = useState(''); const [editing, setEditing] = useState<TripTemplate | null>(null);
  const [name, setName] = useState(sourceTrip?.destination || ''); const [description, setDescription] = useState('');
  const [templateType, setTemplateType] = useState<TripTemplateType>('full_trip');
  const [includeArchived, setIncludeArchived] = useState(false);
  const [data, setData] = useState<TripTemplateData>(() => sourceTrip ? createTemplateDataFromTrip(sourceTrip) : {});
  const templates = useQuery({ queryKey: ['trip-templates', search, templateType, includeArchived], queryFn: () => fetchTripTemplates(search, templateType, includeArchived) });
  const initialTemplate = useQuery({ queryKey: ['trip-template', initialTemplateId], queryFn: () => fetchTripTemplate(initialTemplateId!), enabled: Boolean(initialTemplateId) });
  useEffect(() => { if (initialTemplate.data) setEditing(initialTemplate.data); }, [initialTemplate.data]);
  useEffect(() => { if (!editing) return; setName(editing.name); setDescription(editing.description || ''); setTemplateType(editing.template_type); setData(editing.template_data as unknown as TripTemplateData); }, [editing]);
  const refresh = () => client.invalidateQueries({ queryKey: ['trip-templates'] });
  const save = useMutation({ mutationFn: () => saveTripTemplate(user!.id, { id: editing?.id, name, description, data, templateType }), onSuccess: () => { refresh(); setEditing(null); toast.success(t('trips.templates.saved')); }, onError: () => toast.error(t('trips.templates.sensitive')) });
  const status = useMutation({ mutationFn: ({ id, value }: { id: string; value: 'active' | 'archived' }) => updateTripTemplateStatus(id, value), onSuccess: refresh });
  const remove = useMutation({ mutationFn: softDeleteTripTemplate, onSuccess: refresh });
  const favorite = useMutation({ mutationFn: ({ id, value }: { id: string; value: boolean }) => toggleTripTemplateFavorite(id, value), onSuccess: refresh });
  const duplicate = (template: TripTemplate) => saveTripTemplate(user!.id, { name: `${template.name} ${t('trips.templates.copySuffix')}`, description: template.description || undefined, data: template.template_data as unknown as TripTemplateData }).then(refresh);
  return <div className="fixed inset-0 z-[105] bg-slate-50 dark:bg-slate-950" dir={direction} role="dialog" aria-modal="true" aria-labelledby="templates-title"><header className="flex items-center justify-between border-b border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-950"><h2 id="templates-title" className="text-lg font-bold">{t('trips.templates.title')}</h2><Button size="icon" variant="ghost" onClick={onClose} aria-label={t('trips.close')}><X/></Button></header><main className="mx-auto grid max-w-6xl gap-5 p-4 lg:grid-cols-[minmax(0,1fr)_22rem]">
    <section><div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_12rem_auto]"><label className="relative block"><Search className="absolute start-3 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t('trips.templates.search')} className="h-10 w-full rounded-lg border border-slate-300 bg-white ps-10 pe-3 dark:border-slate-700 dark:bg-slate-900"/></label><select value={templateType} onChange={(event) => setTemplateType(event.target.value as TripTemplateType)} className="h-10 rounded-lg border border-slate-300 bg-white px-3 dark:border-slate-700 dark:bg-slate-900">{(['full_trip','itinerary','hotel','transportation','pricing','checklist','message'] as TripTemplateType[]).map((type) => <option key={type} value={type}>{t(`trips.templates.types.${type}`)}</option>)}</select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={includeArchived} onChange={(event) => setIncludeArchived(event.target.checked)}/>{t('trips.templates.includeArchived')}</label></div><div className="mt-4 space-y-2">{templates.data?.map((template) => <article key={template.id} className="rounded-lg border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><button className="min-w-0 text-start" onClick={() => setEditing(template)}><h3 className="font-semibold">{template.name}</h3><p className="text-sm text-slate-500">{template.description}</p><span className="text-xs text-slate-500">{t(`trips.templates.status.${template.status}`)} · {t('trips.templates.used', { count: template.usage_count })}</span></button><div className="flex"><Button size="icon" variant="ghost" onClick={() => favorite.mutate({ id: template.id, value: !template.is_favorite })} aria-label={t('trips.templates.favorite')}><Star className={`h-4 w-4 ${template.is_favorite ? 'fill-amber-400 text-amber-500' : ''}`}/></Button><Button size="icon" variant="ghost" onClick={() => setEditing(template)} aria-label={t('trips.edit')}><Pencil className="h-4 w-4"/></Button><Button size="icon" variant="ghost" onClick={() => void duplicate(template)} aria-label={t('trips.duplicate.title')}><Copy className="h-4 w-4"/></Button><Button size="icon" variant="ghost" onClick={() => status.mutate({ id: template.id, value: template.status === 'active' ? 'archived' : 'active' })} aria-label={t('trips.archive')}><Archive className="h-4 w-4"/></Button><Button size="icon" variant="danger" onClick={() => remove.mutate(template.id)} aria-label={t('trips.delete')}><Trash2 className="h-4 w-4"/></Button></div></div>{onUse && template.status === 'active' && <Button className="mt-3" variant="primary" onClick={() => { void recordTripTemplateUse(template.id); onUse(templateToTripDraft(template)); onClose(); }}><FilePlus2 className="h-4 w-4"/>{t('trips.templates.use')}</Button>}</article>)}</div></section>
    <section className="rounded-lg border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><h3 className="font-semibold">{editing ? t('trips.templates.edit') : sourceTrip ? t('trips.templates.fromTrip') : t('trips.templates.create')}</h3><label className="mt-3 block text-sm">{t('trips.templates.name')}<input value={name} onChange={(event) => setName(event.target.value)} maxLength={120} className="mt-1 h-10 w-full rounded-lg border border-slate-300 bg-transparent px-3"/></label><label className="mt-3 block text-sm">{t('trips.templates.type')}<select value={templateType} onChange={(event) => setTemplateType(event.target.value as TripTemplateType)} className="mt-1 h-10 w-full rounded-lg border border-slate-300 bg-transparent px-3">{(['full_trip','itinerary','hotel','transportation','pricing','checklist','message'] as TripTemplateType[]).map((type) => <option key={type} value={type}>{t(`trips.templates.types.${type}`)}</option>)}</select></label><label className="mt-3 block text-sm">{t('trips.templates.description')}<textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={3} className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent p-3"/></label><label className="mt-3 block text-sm">{t('trips.destination')}<input value={data.destination || ''} onChange={(event) => setData({ ...data, destination: event.target.value })} className="mt-1 h-10 w-full rounded-lg border border-slate-300 bg-transparent px-3"/></label><label className="mt-3 block text-sm">{t('trips.templates.duration')}<input type="number" min="1" max="365" value={data.duration_days || 1} onChange={(event) => setData({ ...data, duration_days: Number(event.target.value) })} className="mt-1 h-10 w-full rounded-lg border border-slate-300 bg-transparent px-3"/></label><pre className="mt-3 max-h-48 overflow-auto rounded-lg bg-slate-100 p-3 text-xs dark:bg-slate-950">{JSON.stringify(data, null, 2)}</pre><Button className="mt-4 w-full" variant="primary" disabled={!name.trim() || save.isPending} onClick={() => save.mutate()}>{t('trips.save')}</Button></section>
  </main></div>;
}
